line11          db      'loop loop loop loop loop loop loop loop loop loop loop loop loop loop loop loop loop loop',0
line12          db      'loop loop loop loop loop loop loop loop loop loop loop loop loop loop loop loop loop',0
line13          db      'loop loop loop loop loop loop loop loop loop loop loop loop loop loop loop loop',0
line14          db      'loop loop loop loop loop loop loop loop loop loop loop',0
line15          db      'loop loop loop',0
line21          db      'loop loop loop loop loop loop loop loop loop loop loop loop loop',0
line22          db      'loop loop loop loop loop loop loop',0
line23          db      'loop',0
line24          db      'loop loop loop loop loop loop loop loop loop loop loop loop loop loop loop',0
line25          db      'loop loop loop loop loop loop loop loop loop loop loop loop loop loop loop loop loop loop',0
line31          db      'loop loop loop loop loop loop loop loop loop',0
line32          db      'loop loop loop loop loop',0
line33          db      'loop loop',0
line34          db      'loop loop loop loop loop loop loop loop loop loop',0
line35          db      'loop loop loop loop loop loop loop loop loop loop loop loop loop loop loop loop loop loop',0
line41          db      'loop loop loop loop loop loop loop loop',0
line42          db      'loop loop loop loop loop loop loop loop loop loop loop loop loop loop',0
line43          db      'loop loop loop loop',0
line44          db      'loop loop loop loop loop loop',0
line45          db      'loop loop loop loop loop loop loop loop loop loop loop loop',0

lines           dd      line11, line12, line13, line14, line15,\
                        line21, line22, line23, line24, line25,\
                        line31, line32, line33, line34, line35,\
                        line41, line42, line43, line44, line45